=== gayu-thri/fiesta-1/Review2_XML/Gayathri/student_profile_personal/student_profile_personal_xsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="root" type="rootType" />

    <xs:complexType name="rootType">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="profile-personal" type="profile-personalType"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="profile-personalType">
        <xs:sequence maxOccurs="1">

            <xs:element name="student_id" type="IDType" />
            <xs:element name="student_dob" type="dateType"/>
            <xs:element name="student_year_of_study" type="yearType" />
            <xs:element name="student_dept" type="descType" />
            <xs:element name="student_about_myself" type="descType" />
            <xs:element name="student_phone" type="phoneType" />
            <xs:element name="student_school" type="descType" />
            <xs:element name="student_address" type="descType" />
			<xs:element name="student_socialmedia" type="mediaType" />
            
        </xs:sequence>
    </xs:complexType>



    <xs:complexType name="mediaType">
        <xs:sequence>

            <xs:element name="student_socialmedia_1" type="urlType" />
            <xs:element name="student_socialmedia_2" type="urlType" />
            <xs:element name="student_socialmedia_3" type="urlType" />

        </xs:sequence>
    </xs:complexType>



    <xs:simpleType name="phoneType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[1-9][0-9]{9}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="urlType">
        <xs:restriction base="xs:anyURI">
            <xs:pattern value='https?://.+'/>
            <!-- accepts only http:// or https:// URIs. -->
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="yearType">
        <xs:restriction base="xs:integer">
            <xs:pattern value="\d{4}"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="dateType">
        <xs:restriction base="xs:date" />
    </xs:simpleType>

        
    <xs:simpleType name="IDType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"></xs:minInclusive>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="nameType">
        <xs:restriction base="xs:string" />
    </xs:simpleType>

    <xs:simpleType name="descType">
        <xs:restriction base="xs:string">
            <xs:minLength value="10"></xs:minLength>
            <xs:maxLength value="1000"></xs:maxLength>
        </xs:restriction>
    </xs:simpleType>



    <xs:simpleType name="yearType">
        <xs:restriction base="xs:integer">
            <xs:pattern value="\d{4}"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== gayu-thri/fiesta-1/static/Review2_XML/Gayathri/student_profile_personal/validation_p.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE root[
	 
  <!ATTLIST root
  xmlns CDATA #FIXED ''
  xmlns:xsi CDATA #FIXED 'http://www.w3.org/2001/XMLSchema-instance'
  xsi:noNamespaceSchemaLocation NMTOKEN #REQUIRED>
		<!ELEMENT root (profile-personal*)>
		<!ELEMENT profile-personal (student_id, student_dob, student_year_of_study, student_dept, student_about_myself, student_phone, student_school, student_address, student_socialmedia)>

		<!ELEMENT student_socialmedia (student_socialmedia_1, student_socialmedia_2, student_socialmedia_3)>


		<!ELEMENT student_id (#PCDATA)>
		<!ELEMENT student_dob (#PCDATA)>
		<!ELEMENT student_year_of_study (#PCDATA)>
		<!ELEMENT student_dept (#PCDATA)>
		<!ELEMENT student_about_myself (#PCDATA)>
		<!ELEMENT student_phone (#PCDATA)>
		<!ELEMENT student_school (#PCDATA)>
		<!ELEMENT student_address (#PCDATA)>
		<!ELEMENT student_socialmedia_1 (#PCDATA)>   
		<!ELEMENT student_socialmedia_2 (#PCDATA)>
		<!ELEMENT student_socialmedia_3 (#PCDATA)>
		
]>


<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="student_profile_personal_xsd.xsd"> 
    <profile-personal>
        <student_id>1</student_id>
        <student_dob>2001-01-02</student_dob>
        <student_year_of_study> 1</student_year_of_study>
        <student_dept> Computer Science</student_dept>
        <student_about_myself> An athlete who competes in many sports that involve physical strength, speed or endurance. </student_about_myself>
        <student_phone> 9498518293 </student_phone>
        <student_school> Amrita School of Eng.</student_school>
        <student_address> No.123, XYZ Flats, ABC City.</student_address>
        <student_socialmedia>
		
            <student_socialmedia_1> https://twitter.com/dhanushkraja </student_socialmedia_1>
            <student_socialmedia_2> https://www.instagram.com/dhanushkraja </student_socialmedia_2>
            <student_socialmedia_3> https://www.facebook.com/DhanushKRaja </student_socialmedia_3>

        </student_socialmedia>

    </profile-personal>

    
    <profile-personal>

        <student_id>2</student_id>
        <student_dob>2000-11-02</student_dob>
        <student_year_of_study> 2</student_year_of_study>
        <student_dept> Mechanical Engineering</student_dept>
        <student_about_myself> An artist who is passionate in making fresh innovative digital arts. </student_about_myself>
        <student_phone> 9408058096 </student_phone>
        <student_school> Amrita School of Eng.</student_school>
        <student_address> No.432, MNO Flats, ABC City.</student_address>
        <student_socialmedia>

            <student_socialmedia_1> https://www.instagram.com/patrickdempsey </student_socialmedia_1>
            <student_socialmedia_2> https://twitter.com/PatrickDempsey </student_socialmedia_2>
            <student_socialmedia_3> https://www.facebook.com/patrickdempseyofficial </student_socialmedia_3>

        </student_socialmedia>

    </profile-personal>
</root>

=== gayu-thri/fiesta-1/Review2_XML/Gayathri/student_profile_personal/student_profile_personal.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE root SYSTEM "student_profile_personal_dtd.dtd"> -->
<?xml-stylesheet type="text/xsl" href="student_profile_personal_xsl.xsl"?>
<!-- <root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="student_profile_personal_xsd.xsd"> -->
<root>
    <profile-personal>
        <student_id>1</student_id>
        <student_dob>2001-01-02</student_dob>
        <student_year_of_study> 1</student_year_of_study>
        <student_dept> Computer Science</student_dept>
        <student_about_myself> An athlete who competes in many sports that involve physical strength, speed or endurance. </student_about_myself>
        <student_phone> 9498058096 </student_phone>
        <student_school> Amrita School of Eng.</student_school>
        <student_address> No.123, XYZ Flats, ABC City.</student_address>
        <student_socialmedia>

            <student_socialmedia_1> https://twitter.com/dhanushkraja </student_socialmedia_1>
            <student_socialmedia_2> https://www.instagram.com/dhanushkraja </student_socialmedia_2>
            <student_socialmedia_3> https://www.facebook.com/DhanushKRaja </student_socialmedia_3>

        </student_socialmedia>

    </profile-personal>

    
    <profile-personal>

        <student_id>2</student_id>
        <student_dob>2000-11-02</student_dob>
        <student_year_of_study> 2</student_year_of_study>
        <student_dept> Mechanical Engineering</student_dept>
        <student_about_myself> An artist who is passionate in making fresh innovative digital arts. </student_about_myself>
        <student_phone> 9408058096 </student_phone>
        <student_school> Amrita School of Eng.</student_school>
        <student_address> No.432, MNO Flats, ABC City.</student_address>
        <student_socialmedia>

            <student_socialmedia_1> https://www.instagram.com/patrickdempsey </student_socialmedia_1>
            <student_socialmedia_2> https://twitter.com/PatrickDempsey </student_socialmedia_2>
            <student_socialmedia_3> https://www.facebook.com/patrickdempseyofficial </student_socialmedia_3>

        </student_socialmedia>

    </profile-personal>
</root>
