=== gayu-thri/fiesta-1/static/Review2_XML/Prathyusha/table_team_details/team_details.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace = "localfile" xmlns = "localfile" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="team">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="row" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:short" name="id"/>
              <xs:element type="xs:string" name="name"/>
              <xs:element type="xs:byte" name="student_id"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== gayu-thri/fiesta-1/static/Review2_XML/Prathyusha/table_team_details/team_details.xml
<?xml version="1.0" encoding="UTF-8"?>
<team xmlns="localfile" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation = "localfile team_details.xsd">
<row>
   <id>210</id>
   <name>Igniters</name>
   <student_id>1</student_id>
</row>
<row>
   <id>212</id>
   <name>Shilesh</name>
   <student_id>5</student_id>
</row>
<row>
   <id>214</id>
   <name>Tritons</name>
   <student_id>5</student_id>
</row>
<row>
   <id>216</id>
   <name>Gayu</name>
   <student_id>1</student_id>
</row>
<row>
   <id>218</id>
   <name>Rangers</name>
   <student_id>4</student_id>
</row>

</team>
