=== gayu-thri/fiesta-1/static/Review2_XML/Sanjay/9 - Table_Event_Winners/xml_xsd_xsl/9_table_event_winners.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="event_winners">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="row"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="row">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="event_id"/>
                <xs:element ref="team_id"/>
                <xs:element ref="position"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
	<xs:element name="event_id">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="1"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
	<xs:element name="team_id">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="1"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
	<xs:element name="position">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="1"/>
				<xs:maxInclusive value="10"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
</xs:schema>

=== gayu-thri/fiesta-1/Review2_XML/Sanjay/9 - Table_Event_Winners/xml_xsd_xsl/9_table_event_winners.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="9_table_event_winners_style.xsl" type="text/xsl"?>


<event_winners xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="9_table_event_winners.xsd">
	<row>	
		<event_id>12</event_id>
		<team_id>1</team_id>
		<position>1</position>
	</row>
	<row>	
		<event_id>12</event_id>
		<team_id>2</team_id>
		<position>2</position>
	</row>
	<row>	
		<event_id>13</event_id>
		<team_id>3</team_id>
		<position>1</position>
	</row>
	<row>	
		<event_id>14</event_id>
		<team_id>4</team_id>
		<position>1</position>
	</row>
	<row>	
		<event_id>14</event_id>
		<team_id>5</team_id>
		<position>2</position>
	</row>
	<row>	
		<event_id>14</event_id>
		<team_id>6</team_id>
		<position>3</position>
	</row>
</event_winners>
