=== gayu-thri/fiesta-1/static/Review2_XML/Sanjay/4 - Table_Contactus/xml_xsd_xsl/4_table_contactus.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="contactus">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="row"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="row">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="contact_id"/>
                <xs:element ref="contact_name"/>
                <xs:element ref="contact_phone"/>
                <xs:element ref="contact_email"/>
                <xs:element ref="contact_message"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
	<xs:element name="contact_id">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="1"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="contact_name" type="xs:string"/>
	<xs:element name="contact_phone">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[0-9]{10}"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
	<xs:element name="contact_email">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="([0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
	<xs:element name="contact_message">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:whiteSpace value="preserve"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

</xs:schema>

=== gayu-thri/fiesta-1/static/Review2_XML/Sanjay/4 - Table_Contactus/xml_xsd/4_table_contactus.xml
<?xml version="1.0" encoding="UTF-8"?>


<contactus xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="4_table_contactus.xsd">
	<row>
		<contact_id>1</contact_id>
		<contact_name>Krishna Teja</contact_name>
		<contact_phone>1878987656</contact_phone>
		<contact_email>teja@gmail.com</contact_email>
		<contact_message>Registration form is nopt working.</contact_message>
	</row>
	<row>
		<contact_id>2</contact_id>
		<contact_name>Ravi Varma</contact_name>
		<contact_phone>9645678765</contact_phone> 
		<contact_email>ravi@yahoo.co.in</contact_email>
		<contact_message>I am not able to register for solo events. It shows error.</contact_message>
	</row>
	<row>
		<contact_id>3</contact_id>
		<contact_name>Hari Krishna</contact_name>
		<contact_phone>8907656564</contact_phone>
		<contact_email>hari@gmail.com</contact_email>
		<contact_message>Upcoming events are not updated.</contact_message>
	</row>
	<row>
		<contact_id>4</contact_id>
		<contact_name>Paul</contact_name>
		<contact_phone>9877612342</contact_phone>
		<contact_email>paul@amrita.edu</contact_email>
		<contact_message>Can students from other colleges, register?</contact_message>
	</row>
</contactus>
