=== gayu-thri/fiesta-1/Review2_XML/Shilesh/6_table_event/table_event_dtd.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT root (event*)>
<!ELEMENT event (event_id, event_name, event_desc, event_tags, event_type_participation, event_timing, event_venue, event_max_participants, event_registration_link,event_organizer)>

<!ELEMENT event_tags (tag*)>
<!ELEMENT tag (#PCDATA)>

<!ATTLIST tag id CDATA #REQUIRED>
<!ATTLIST tag displayName CDATA #REQUIRED>

<!ELEMENT event_timing (event_start_datetime, event_end_datetime)>
<!ELEMENT event_start_datetime (#PCDATA)>
<!ELEMENT event_end_datetime (#PCDATA)>

<!ELEMENT event_organizer (event_organizer_intracollege, event_organizer_other, event_organizer_name, event_organizer_email, event_organizer_phone, event_organizer_details, event_organizer_poster)>
<!ELEMENT event_organizer_intracollege (event_organizer_college, event_organizer_campus)>
<!ELEMENT event_organizer_college (#PCDATA)>
<!ELEMENT event_organizer_campus (#PCDATA)>

<!ELEMENT event_id (#PCDATA)>
<!ELEMENT event_name (#PCDATA)>
<!ELEMENT event_desc (#PCDATA)>
<!ELEMENT event_type_participation (#PCDATA)>
<!ELEMENT event_venue (#PCDATA)>
<!ELEMENT event_max_participants (#PCDATA)>
<!ELEMENT event_registration_link (#PCDATA)>
<!ELEMENT event_organizer_other (#PCDATA)>
<!ELEMENT event_organizer_name (#PCDATA)>
<!ELEMENT event_organizer_email (#PCDATA)>
<!ELEMENT event_organizer_phone (#PCDATA)>
<!ELEMENT event_organizer_details (#PCDATA)>
<!ELEMENT event_organizer_poster (#PCDATA)>

=== gayu-thri/fiesta-1/Review2_XML/Shilesh/6_table_event/table_event.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "table_event_dtd.dtd">
<root>
    <event>
        <event_id>1</event_id>
        <event_name>ICPC</event_name>
        <event_desc>5 coding questions in 2 hrs</event_desc>
        <event_tags>
            <tag>coding</tag>
        </event_tags>
        <event_type_participation>Team</event_type_participation>
        <event_timing>
            <event_start_datetime></event_start_datetime>
            <event_end_datetime></event_end_datetime>
        </event_timing>
        <event_venue>AB2 CP Lab2</event_venue>
        <event_max_participants>100</event_max_participants>
        <event_registration_link></event_registration_link>
        <event_organizer>
            <event_organizer_intracollege>
                <event_organizer_college>Amrita</event_organizer_college>
                <event_organizer_campus>Coimbatore</event_organizer_campus>
            </event_organizer_intracollege>
            <event_organizer_other></event_organizer_other>
            <event_organizer_name>Dr.Abc</event_organizer_name>
            <event_organizer_email>abc@gmail.com</event_organizer_email>
            <event_organizer_phone>1234567890</event_organizer_phone>
            <event_organizer_details>asdfqwer</event_organizer_details>
            <event_organizer_poster></event_organizer_poster>
        </event_organizer>
    </event>
    <event>
        <event_id>2</event_id>
        <event_name>Painting</event_name>
        <event_desc>Paint a potrait in 2 hrs</event_desc>
        <event_tags>
            <tag>painting</tag>
            <tag>potrait</tag>
        </event_tags>
        <event_type_participation>solo</event_type_participation>
        <event_timing>
            <event_start_datetime></event_start_datetime>
            <event_end_datetime></event_end_datetime>
        </event_timing>
        <event_venue>AB1</event_venue>
        <event_max_participants>100</event_max_participants>
        <event_registration_link></event_registration_link>
        <event_organizer>
            <event_organizer_intracollege>
                <event_organizer_college>Amrita</event_organizer_college>
                <event_organizer_campus>Coimbatore</event_organizer_campus>
            </event_organizer_intracollege>
            <event_organizer_other></event_organizer_other>
            <event_organizer_name>Mr.XYZ</event_organizer_name>
            <event_organizer_email>xyz@gmail.com</event_organizer_email>
            <event_organizer_phone>9876543210</event_organizer_phone>
            <event_organizer_details>poiuyqwer</event_organizer_details>
            <event_organizer_poster></event_organizer_poster>
        </event_organizer>
    </event>
</root>
