<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE root[
	 
  <!ATTLIST root
  xmlns CDATA #FIXED ''
  xmlns:xsi CDATA #FIXED 'http://www.w3.org/2001/XMLSchema-instance'
  xsi:noNamespaceSchemaLocation NMTOKEN #REQUIRED>

	 <!ELEMENT root (achievement)*> 
	 <!ELEMENT achievement (student_id,student_achievement)> 
	 <!ELEMENT student_id (#PCDATA)> 
	 <!ELEMENT student_achievement (#PCDATA)>
]>

<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="student_profile_achievement_xsd.xsd"> 

    <achievement>
    	<student_id> 1 </student_id>
    	<student_achievement> Awarded as the best stand-up comedian and got second place in intra-basketball event</student_achievement>
    </achievement>

    <achievement>
    	<student_id> 2 </student_id>
    	<student_achievement> Got first place in the swimming competition conducted during the fest and got a consolation prize in drawing marathon
    	</student_achievement>
    </achievement>
	
</root>

